# Generated by Django 4.2.10 on 2024-03-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
