# Generated by Django 4.2.10 on 2024-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('W', 'Walk'), ('R', 'Run'), ('B', 'Bike'), ('R', 'Rollerblade')], default='W', max_length=20),
        ),
    ]
