# Generated by Django 4.2.10 on 2024-03-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('W', 'Walk'), ('R', 'Run'), ('B', 'Bike'), ('RO', 'Rollerblade')], default='W', max_length=20),
        ),
    ]
